KING:
  comment_format:
    - "xform/ /\\ |\\ /"
    - "xform/$/〕/"
    - "xform/^/〔/"
  dictionary: cqlb
  overwrite_comment: false
  tags:
    - King
__build_info:
  rime_version: 1.4.0
  timestamps:
    cqlb_pinyin.custom: 0
    cqlb_pinyin.schema: 1550069497
    default: 1530753503
    default.custom: 1550284196
custom_movetop:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: 2
  user_dict: cqlb_user_movetop
custom_userdict:
  db_class: stabledb
  dictionary: ""
  enable_completion: false
  enable_sentence: false
  initial_quality: "-1"
  user_dict: cqlb_userdict
engine:
  filters:
    - "reverse_lookup_filter@i_reverse_lookup"
    - "reverse_lookup_filter@KING"
    - simplifier
    - uniquifier
  processors:
    - ascii_composer
    - recognizer
    - key_binder
    - speller
    - punctuator
    - selector
    - navigator
    - express_editor
  segmentors:
    - ascii_segmentor
    - matcher
    - abc_segmentor
    - punct_segmentor
    - fallback_segmentor
  translators:
    - punct_translator
    - table_translator
    - "table_translator@custom_userdict"
    - "table_translator@custom_movetop"
    - "table_translator@pinyin_hunshu"
    - "table_translator@ihunshu"
i_reverse_lookup:
  comment_format:
    - "xform/ /\\ |\\ /"
    - "xform/$/ 〕/"
    - "xform/^/〔 /"
  dictionary: cqlb
  overwrite_comment: false
  tags:
    - i_reverse_lookup_pattern
ihunshu:
  db_class: stabledb
  dictionary: iFC
  enable_completion: true
  enable_sentence: false
  enable_user_dict: false
  initial_quality: 0
  user_dict: ""
key_binder:
  bindings:
    - {accept: "Control+p", send: Up, when: composing}
    - {accept: "Control+n", send: Down, when: composing}
    - {accept: "Control+b", send: Left, when: composing}
    - {accept: "Control+f", send: Right, when: composing}
    - {accept: "Control+a", send: Home, when: composing}
    - {accept: "Control+e", send: End, when: composing}
    - {accept: "Control+d", send: Delete, when: composing}
    - {accept: "Control+k", send: "Shift+Delete", when: composing}
    - {accept: "Control+h", send: BackSpace, when: composing}
    - {accept: "Control+g", send: Escape, when: composing}
    - {accept: "Control+bracketleft", send: Escape, when: composing}
    - {accept: "Alt+v", send: Page_Up, when: composing}
    - {accept: "Control+v", send: Page_Down, when: composing}
    - {accept: ISO_Left_Tab, send: "Shift+Left", when: composing}
    - {accept: "Shift+Tab", send: "Shift+Left", when: composing}
    - {accept: Tab, send: "Shift+Right", when: composing}
    - {accept: minus, send: Page_Up, when: has_menu}
    - {accept: equal, send: Page_Down, when: has_menu}
    - {accept: comma, send: Page_Up, when: paging}
    - {accept: period, send: Page_Down, when: has_menu}
    - {accept: "Control+Shift+1", select: .next, when: always}
    - {accept: "Control+Shift+2", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+3", toggle: full_shape, when: always}
    - {accept: "Control+Shift+4", toggle: simplification, when: always}
    - {accept: "Control+Shift+5", toggle: extended_charset, when: always}
    - {accept: "Control+Shift+exclam", select: .next, when: always}
    - {accept: "Control+Shift+at", toggle: ascii_mode, when: always}
    - {accept: "Control+Shift+numbersign", toggle: full_shape, when: always}
    - {accept: "Control+Shift+dollar", toggle: simplification, when: always}
    - {accept: "Control+Shift+percent", toggle: extended_charset, when: always}
    - {accept: "Shift+space", toggle: full_shape, when: always}
    - {accept: "Control+period", toggle: ascii_punct, when: always}
    - {accept: "Shift+space", toggle: noop, when: always}
  import_preset: default
menu:
  page_size: 6
pinyin_hunshu:
  db_class: stabledb
  dictionary: pyHS
  enable_completion: true
  enable_sentence: false
  enable_user_dict: false
  initial_quality: "-10"
  user_dict: ""
punctuator:
  full_shape:
    " ": {commit: "　"}
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": ["＃", "⌘"]
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["％", "°", "℃"]
    "&": "＆"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["＊", "·", "・", "×", "※", "❂"]
    "+": "＋"
    ",": {commit: "，"}
    "-": "－"
    .: {commit: "。"}
    "/": "、"
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "＝"
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": ["＠", "☯"]
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "｀"
    "{": ["『", "〖", "｛"]
    "|": ["·", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": "～"
  half_shape:
    "!": {commit: "！"}
    "\"": {pair: ["“", "”"]}
    "#": "#"
    "$": ["￥", "$", "€", "£", "¥", "¢", "¤"]
    "%": ["%", "％", "°", "℃"]
    "&": "&"
    "'": {pair: ["‘", "’"]}
    "(": "（"
    ")": "）"
    "*": ["*", "＊", "·", "・", "×", "※", "❂"]
    "+": "+"
    ",": {commit: "，"}
    "-": "-"
    .: {commit: "。"}
    "/": "、"
    ":": {commit: "："}
    ";": {commit: "；"}
    "<": ["《", "〈", "«", "‹"]
    "=": "="
    ">": ["》", "〉", "»", "›"]
    "?": {commit: "？"}
    "@": "@"
    "[": ["「", "【", "〔", "［"]
    "\\": ["、", "\\", "＼"]
    "]": ["」", "】", "〕", "］"]
    "^": {commit: "……"}
    _: "——"
    "`": "`"
    "{": ["『", "〖", "｛"]
    "|": ["·", "|", "｜", "§", "¦"]
    "}": ["』", "〗", "｝"]
    "~": ["~", "～"]
  import_preset: default
recognizer:
  import_preset: default
  patterns:
    King: "^.....[a-z]+'?$"
    email: "^[A-Za-z][-_.0-9A-Za-z]*@.*$"
    i_reverse_lookup_pattern: "^i[a-z;,./]+$"
    punct: "^/([0-9]0?|[A-Za-z]+)$"
    uppercase: "[A-Z][-_+.'0-9A-Za-z]*$"
    url: "^(www[.]|https?:|ftp[.:]|mailto:|file:).*$"
schema:
  author:
    - "超强两笔制作人：付东升"
  dependencies:
    - pyHS
    - iFC
  description: "超强两笔混输。"
  name: "超强两笔混输"
  schema_id: cqlb_pinyin
  version: 5.1
simplifier:
  opencc_config: s2t.json
  option_name: traditional
speller:
  alphabet: "abcdefghijklmnopqrstuvwxyz;,./"
  auto_clear: auto
  auto_select: true
  initials: abcdefghijklmnopqrstuvwxyz
switches:
  - name: ascii_mode
    reset: 0
    states: ["中文", "西文"]
  - name: full_shape
    states: ["半角", "全角"]
  - name: traditional
    states: [ 汉字, 漢字 ]
  - name: ascii_punct
    states: [ 。，, ．， ]
translator:
  dictionary: cqlb
  enable_charset_filter: false
  enable_completion: true
  enable_encoder: true
  enable_sentence: false
  enable_user_dict: false
  encode_commit_history: true
  max_phrase_length: 4
